version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true

submodules:
  include:
    - src/authnexus

analytics:
  google_analytics_id: 337774086 

environment:
  variables:
    AUTHNEXUS_DOCS_MODE: production
    PYTHONPATH: $PYTHONPATH:./src
